<?php

namespace Database\Seeders;

use App\Models\Barangay;
use Illuminate\Database\Seeder;

class BarangaySeeder extends Seeder
{
    public function run(): void
    {
        $barangays = [
            'Abanon',
            'Agdao',
            'Anando',
            'Ano',
            'Antipangol',
            'Aponit',
            'Bacnar',
            'Balaya',
            'Balayong',
            'Baldog',
            'Balite Sur',
            'Balococ',
            'Bani',
            'Bega',
            'Bocboc',
            'Bugallon-Posadas Street',
            'Bogaoan',
            'Bolingit',
            'Bolosan',
            'Bonifacio',
            'Buenglat',
            'Burgos Padlan',
            'Cacaritan',
            'Caingal',
            'Calobaoan',
            'Calomboyan',
            'Capataan',
            'Caoayan-Kiling',
            'Cobol',
            'Coliling',
            'Cruz',
            'Doyong',
            'Gamata',
            'Guelew',
            'Ilang',
            'Inerangan',
            'Isla',
            'Libas',
            'Lilimasan',
            'Longos',
            'Lucban',
            'Mabalbalino',
            'Mabini',
            'Magtaking',
            'Malacañang',
            'Maliwara',
            'Mamarlao',
            'Manzon',
            'Matagdem',
            'Mestizo Norte',
            'Naguilayan',
            'Nilentap',
            'Padilla-Gomez',
            'Pagal',
            'Palaming',
            'Palaris',
            'Palospos',
            'Pangalangan',
            'Pangoloan',
            'Pangpang',
            'Paitan-Panoypoy',
            'Parayao',
            'Payapa',
            'Payar',
            'Perez Boulevard',
            'Polo',
            'Quezon Boulevard',
            'Quintong',
            'Rizal',
            'Roxas Boulevard',
            'Salinap',
            'San Juan',
            'San Pedro-Taloy',
            'Sapinit',
            'PNR Station Site',
            'Supo',
            'Talang',
            'Tamayo',
            'Tandoc',
            'Tarece',
            'Tarectec',
            'Tayambani',
            'Tebag',
            'Turac',
            'M. Soriano',
            'Tandang Sora',
        ];

        foreach ($barangays as $index => $barangay) {
            Barangay::query()->updateOrCreate(
                ['name' => $barangay],
                [
                    'code' => 'BRGY' . str_pad((string) ($index + 1), 2, '0', STR_PAD_LEFT),
                    'status' => 'active',
                ],
            );
        }
    }
}
